### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by vansera** [lucasmonstro/pytibia#29]
quando tento rodar o arquivo main.py ele fica 'rodando' e nada acontece ... quando eu clico em stop ele da esse erro

```
Traceback (most recent call last):
  File "C:\Users\vanse\OneDrive\Documentos\GitHub\pytibia\main.py", line 288, in <module>
    main()
  File "C:\Users\vanse\OneDrive\Documentos\GitHub\pytibia\main.py", line 283, in main
    time.sleep(10)
KeyboardInterrupt
```

[https://imgur.com/gnPi7hJ]

 - OS: [e.g. iOS, Windows] w10
 - Tibia Version [e.g. 13.05.12613]

**Comment by lucasmonstro** [comment]
Salve Vansera, o bot está em desenvolvimento, atualmente funcionando como um SDK. Vou por isso no README, até o fim do mês eu tenho uma v0 funcional.

Me adiciona no discord lucasmonstro#7433
