### ISSUE TITLE
[BUG] - DXCamera problem

### ISSUE THREAD

**Issue by Rastafaraaj** [lucasmonstro/PyTibia#52]
Exception in thread DXCamera:
Traceback (most recent call last):
  File "c:\users\pc\appdata\local\programs\python\python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "c:\users\pc\appdata\local\programs\python\python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\PC\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-Cxjxipsr-py3.9\lib\site-packages\dxcam\dxcam.py", line 161, in __capture
    self.__timer_handle = create_high_resolution_timer()
  File "C:\Users\PC\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-Cxjxipsr-py3.9\lib\site-packages\dxcam\util\timer.py", line 20, in create_high_resolution_timer
    raise ctypes.WinError()
OSError: [WinError 87] The parameter is incorrect.

I'm running on bit oldie hardware, and my graphic card doesn't have CUDA, maybe that's why but i cannot be sure.

**Comment by lucasmonstro** [comment]
Can you give me your hardware specs?

**Comment by Rastafaraaj** [comment]
Hello, I'm sorry but my previous pc has been destroyed for parts and sold.
What I remember:
HP XW6600,
Xeon,
32GB RAM DDR2,
2gb GPU but I don't remember anything about it


niedz., 23 kwi 2023, 14:43 użytkownik Lucas Monstro <
***@***.***> napisał:

**Comment by Rastafaraaj** [comment]
Windows 10 64 bit

niedz., 23 kwi 2023, 15:09 użytkownik Kamil Kamil ***@***.***>
napisał:

**Comment by lucasmonstro** [comment]
Looks like a dxcam issue. Can you try to open issue in dxcam project?

**Comment by lucasmonstro** [comment]
Have news?

**Comment by lucasmonstrox** [comment]
Can you try again?
