### ISSUE TITLE
[BUG] - Fail to start app

### ISSUE THREAD

**Issue by arthurl31** [lucasmonstro/PyTibia#54]
Error running: poetry run python main.py

CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\arthu\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\arthu\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1306, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\scheduler\timeoutscheduler.py", line 83, in interval
    sad.disposable = self.invoke_action(action, state)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\scheduler\scheduler.py", line 103, in invoke_action
    ret = action(self, state)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\scheduler\periodicscheduler.py", line 47, in periodic
    state = action(state)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observable\timer.py", line 76, in action
    observer.on_next(count)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\map.py", line 41, in on_next
    obv.on_next(result)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\filter.py", line 34, in on_next
    observer.on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\filter.py", line 34, in on_next
    observer.on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\map.py", line 41, in on_next
    obv.on_next(result)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\map.py", line 39, in on_next
    obv.on_error(err)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 34, in on_error
    self._on_error(error)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 34, in on_error
    self._on_error(error)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 34, in on_error
    self._on_error(error)
  [Previous line repeated 9 more times]
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\internal\basic.py", line 34, in default_error
    raise err
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\map.py", line 37, in on_next
    result = _mapper(value)
  File "C:\Users\arthu\Documents\PyTibia\main.py", line 223, in handleBattleListCreatures
    hasBattleListCreatures = len(gameContext['battleListCreatures']) > 0
TypeError: object of type 'NoneType' has no len()

**Comment by lucasmonstro** [comment]
Try again, PyTibia is not using CUDA anymore.

**Comment by arthurl31** [comment]
CUDA is not warning anymore but the error continues:
```

PS C:\Users\arthu\Documents\PyTibia> poetry run python main.py  
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\arthu\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\arthu\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1306, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\scheduler\timeoutscheduler.py", line 83, in interval
    sad.disposable = self.invoke_action(action, state)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\scheduler\scheduler.py", line 103, in invoke_action
    ret = action(self, state)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\scheduler\periodicscheduler.py", line 47, in periodic
    state = action(state)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observable\timer.py", line 76, in action
    observer.on_next(count)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\map.py", line 41, in on_next
    obv.on_next(result)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\filter.py", line 34, in on_next
    observer.on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\filter.py", line 34, in on_next
    observer.on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\map.py", line 41, in on_next
    obv.on_next(result)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 26, in on_next
    self._on_next(value)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\map.py", line 39, in on_next
    obv.on_error(err)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 34, in on_error
    self._on_error(error)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 34, in on_error
    self._on_error(error)
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\observer\autodetachobserver.py", line 34, in on_error
    self._on_error(error)
  [Previous line repeated 9 more times]
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\internal\basic.py", line 34, in default_error
    raise err
  File "C:\Users\arthu\AppData\Local\pypoetry\Cache\virtualenvs\pytibia-L9h-_N0o-py3.9\lib\site-packages\rx\core\operators\map.py", line 37, in on_next
    result = _mapper(value)
  File "C:\Users\arthu\Documents\PyTibia\main.py", line 223, in handleBattleListCreatures
    hasBattleListCreatures = len(gameContext['battleListCreatures']) > 0
TypeError: object of type 'NoneType' has no len()
```

**Comment by lucasmonstro** [comment]
do you still have errors?

**Comment by lucasmonstro** [comment]
@arthurl31 I will create a tutorial to explain what configs you need to have to start bot without any problem. Also, I accept pull request 👍🏼
